### PR TITLE
New publication

### PR DESCRIPTION
**Pull request by SimonOuellette35**
# Description

Adding a new publication to the list:

[Conviction-Based Planning for Sparse Reward Reinforcement Learning Problems](https://openreview.net/pdf?id=hbEVCxTBe6)(UQÀM, PRL @ ICAPS 2024)

### CODE REVIEW

**Review by pseudo-rnd-thoughts — COMMENTED** [review]
Congrats on the paper, currently the openreview reports a 404 error. 
I believe this means the paper isn't public yet. I'm guessing that this will happen soon

**Comment by SimonOuellette35** [comment]
> Congrats on the paper, currently the openreview reports a 404 error. I believe this means the paper isn't public yet. I'm guessing that this will happen soon

Yes, my bad. This is a private link -- I thought it was public. I should have a public version available by June 2nd.

**Comment by pseudo-rnd-thoughts** [comment]
No worries, ignore pre-commit failing that is due to other issues
Update the PR when you have a public link and I can merge

**Comment by SimonOuellette35** [comment]
Hi, I updated the PR with the correct, public URL.

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Pull request merged**
